### ISSUE TITLE
Projectile Velocity

### ISSUE THREAD

**Issue by Retroeer** [HalendSoftware/Inferno#4]
Our current implementation just sucks. 

![Image](https://github.com/HalendSoftware/Inferno/assets/44037603/7fa7e6f1-79a7-406e-8ec1-2e66be3f8213)

https://github.com/HalendSoftware/Inferno/assets/44037603/c06adbb5-50ef-4ec7-8822-4414ca6a1e82

![Image](https://github.com/HalendSoftware/Inferno/assets/44037603/93010fea-5984-46f1-b77c-1b760dd182c5)

**Comment by cohaereo** [comment]
You know what they say, measure twice, cut once. I'm getting around 42 m/s on a larger distance (59 meters over 1.4s ~= 42.14 m/s)

https://github.com/HalendSoftware/Inferno/assets/25546261/440dcee5-62c3-4151-9316-206290fee4e6


![Image](https://github.com/HalendSoftware/Inferno/assets/25546261/45225692-ab64-4a30-8393-c7a26b1bffd8)

**Comment by Retroeer** [comment]
lgtm!
